var NameGenerator = {
    levelName: function() {
        var nameSources = {
            adj: ["Abysmal","Adamantine","Ancient","Angry","Arching","Arctic","Arid","Bare","Beholding","Bellowing","Black","Bleak","Blue","Boiling","Bottomless","Boundless","Brilliant","Bronze","Burned","Burning","Calm","Calmest","Charmed","Cheerless","Climbing","Cobalt","Cold","Collapsing","Colorless","Colossal","Coral","Crystal","Cunning","Cursed","Dancing","Dangerous","Dark","Darkest","Dead","Decayed","Decaying","Deep","Deepest","Dense","Depraved","Deserted","Desolate","Desolated","Diamond","Distant","Dread","Dreaded","Dreadful","Dreary","Dry","Eastern","Emerald","Empty","Enchanted","Enormous","Eroded","Ethereal","Ever Reaching","Everlasting","Fabled","Faraway","Farthest","Feared","Fearsome","Fiery","Flaring","Flat","Flowing","Foaming","Forbidden","Forbidding","Fractured","Frightening","Frozen","Gargantuan","Giant","Gigantic","Glassy","Gleaming","Glistening","Gloomy","Glowing","Gold","Golden","Grave","Gray","Green","Grim","Harmonious","Haunted","Heaving","Hellish","Hollow","Homeless","Hopeless","Hot","Huge","Humongous","Hungry","Immense","Infernal","Infinite","Invisible","Iron","Isolated","Jade","Jagged","Killing","Laughing","Lifeless","Light","Lightest","Living","Lonely","Lucent","Majestic","Malevolent","Malicious","Mammoth","Mesmerizing","Mighty","Mirrored","Misty","Moaning","Molten","Monotonous","Monstrous","Motionless","Mysterious","Narrow","Neverending","New","Northern","Open","Orient","Overhanging","Parched","Peaceful","Perfumed","Plain","Pleasant","Prickly","Primeval","Quiet","Raging","Red","Relentless","Remote","Restless","Rocking","Rocky","Rough","Rugged","Sad","Sandy","Sanguine","Savage","Scarlet","Scorching","Serene","Severed","Shadow","Shadowed","Shadowy","Shimmering","Silent","Silver","Sleeping","Slumbering","Slumbrous","Sly","Soundless","Southern","Spacious","Sparkling","Sterile","Stern","Straitened","Sunny","Symmetrical","Teal","Terraced","Terrestrial","Throbbing","Thundering","Tinted","Titanic","Tranquil","Treacherous","Troubled","Turbulent","Turquoise","Twisting","Ugly","Uncanny","Unfathomed","Uninviting","Unknown","Unresting","Unruffled","Unscaled","Unstable","Unwelcoming","Vast","Violent","Voiceless","Volcanic","Walled","Wasted","Wasteful","Wasting","Welcoming","Western","Whelming","Whispering","White","Wild","Windless","Windy","Withered","Wondering","Wrinkled","Yearning","Yelling","Yellow",
                  //"Abandoned","Abominable","Abomination","Abysmal","Abyss","Adamantine","Adamantite","Ancient","Angry","Arcane","Arching","Arctic","Arid","Bare","Bellowing","Black","Black Forest","Black Mountain","Bleak","Bloodfall","Bloodlust","Boiling","Bottomless","Brilliant","Broken Bones","Broken Curse","Bronze","Brutal","Buried","Burned","Burning","Burning Forest","Buried","Chaos","Chaotic","Cobalt","Cold","Collapsing","Coral","Courage","Crescent Moon","Crystal","Cunning","Cursed","Damned","Dancing","Dark","Daydream","Dead","Deadly","Death Talon","Decayed","Decaying","Deep","Deepest","Deepwood","Delusion","Demonic","Depraved","Desert","Deserted","Desolate","Desolated","Destroyed","Destruction","Diamond","Dire","Distant","Dragon","Dragonclaw","Dragontooth","Dread","Dreaded","Dreadful","Dream","Dreary","Dry","Dying","Earth","Eastern","Eclipse","Emerald","Empty","Enchanted","Ender","Erased","Eternal","Eternal Agony","Eternal Rest","Ethereal","Fabled","Fallen Legion","False","Feared","Fearsome","Fire","Fire Mountain","Flowing","Foaming","Forbidden","Forgotten","Forsaken","Fractured","Frozen","Full Moon","Ghost","Glistening","Gloomy","Glowing","Goblin","Gold Mine","Grey","Grim","Grizzly","Hallucination","Haunted","Hidden","Hollow","Howling","Hungry","Illusion","Infernal","Infinite","Invisible","Iron","Iron Mine","Ironbark","Isolated","Jade","Jagged","Killing","Laughing","Laughing Skulls","Lifeless","Light","Lion Tooth","Living","Living Dead","Lonely","Lost","Lower","Lucent","Lurking Shadow","Malicious","Mesmerizing","Mighty","Mirage","Mirrored","Misty","Mithril","Mithril Mine","Moaning","Mocking","Molten","Motionless","Mourning","Murky","Mysterious","Mystic","Narrow","Nether","Neverending","Nightmare","Northern","Obliterated","Oblivion","Ogre","Oracle","Orc","Overhanging","Perfumed","Phantom","Phoenix","Prisoner","Quiet","Raging","Red","Restless","Roaring","Rocking","Rugged","Sad","Sanguine","Savage","Scarlet","Scheming","Scorching","Screaming","Secret","Serene","Shadow","Shadowed","Shadowy","Shimmering","Shrieking","Silent","Silver","Sleeping","Smoky","Smoldering","Sorrow","Southern","Specter","Spirit","Steel","Sterile","Sunken","Swamp","Terraced","Thief","Thundering","Tormented","Tranquil","Turbulent","Twilight","Twisted","Twisting","Unholy","Unknown","Unstable","Vicious","Violent","Voiceless","Voiceless Whimpers","Volcanic","Wailing","Wasted","Watching Eyes","Western","Whispering","Whispering Shadows","White","White Forest","Wicked","Wild","Wind","Windy","Winter","Withered","Wondering","Wraith","Wrath","Yawning"
                  "Black","White","Silver","Golden","Crystal","Fallen","Ghost","Phantom","Hidden","Secret","Hopeless","Forsaken","Gentle","Chaotic","Conquered","Burning","Poisoned","Whispering","Mourning","Crying","Lost","Infernal","Vanished","Rejected","Neglected","Shunned","Impostor","Renegade","Betrayed","Vanquished","Burning","Frozen","Destroyed","Cursed","Ancient","Obsidian","Ebon","Forbidden","Lonely","Nameless","Dark","Cold","Haunted","Forgotten","Scarlet","Shrouded","Uncanny","Unspoken","Vanishing","Nightmare","Mystic","Mythic","Enigmatic","Doomed","Death's","Spirit","Spirit's","Unknown","Shadow","Elemental","Savage","Storm","Thunder","Barbaric","Cruel","Brutal","Blooded","Ruthless","Raging","Furious","Mad","Granite","Dishonored","Perished",
                  "Abandoned","Abyss","Agony","Ashen","Bare","Barren","Bleak","Blight","Bone","Broken","Burning","Chaos","Charcoal","Coal","Cobalt","Collapsed","Corroded","Cracking","Crimson","Crumbled","Crumbling","Cursed","Damned","Dark","Dcayed","Dead","Debris","Decaying","Deserted","Desolated","Desolation","Despair","Destroyed","Destruction","Dismissed","Doom","Dread","Emptied","Empty","End","Ender","Erased","Ethereal","Exile","Exiled","Extinct","Fallen","Fire","Foggy","Forgotten","Forsaken","Fragmented","Frozen","Ghost","Gloom","Grave","Haunted","Ice","Illusion","Infernal","Inferno","Isolated","Isolation","Lifeless","Lonely","Lost","Mist","Molded","Molten","Motionless","Murky","Mythic","Nameless","Necrotic","Neglected","Night","Nightmare","Nullified","Obliterated","Oblivion","Obsidian","Onyx","Overgrown","Perished","Petrified","Phantom","Remnant","Residue","Rotting","Rubble","Ruin","Ruined","Rusted","Savage","Scorching","Scourge","Scream","Screaming","Shadow","Shamble","Shrub","Silent","Silver","Skeleton","Skull","Slate","Sleeping","Sleepy","Smoke","Solitude","Soot","Spirit","Stone","Twilight","Uncanny","Undone","Unknown","Vanquished","Vibrating","Void","Waste","Wasted","Weeping","Whisper","Whispering","Windy","Wreckage"
                 ],
            noun: [
                "Lemonade Stand","Store","Street", // ducks!
                "Cave","Cavern","Grotto","Den","Cavity","Hollow","Hollows","Caves","Caverns","Hole","Hideout","Shelter","Overhang","Sanctuary","Subterrane",
                "Burrows","Catacombs","Cells","Chambers","Crypt","Delves","Dungeon","Grotto","Haunt","Labyrinth","Lair","Maze","Pits","Point","Quarters","Tombs","Tunnels","Vault"
                ],
        };
        return "The " + nameSources.adj.choose() + " " + nameSources.noun.choose();
    }
};
